name: bundle

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  bundle:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v4

    - name: Install procon-bundler for Rust
      uses: baptiste0928/cargo-install@v3
      with:
        crate: procon-bundler
        git: https://github.com/ngtkana/procon-bundler

    - name: Bundle hayatlib into bundle.rs
      run: |
        procon-bundler bundle ../hayatlib > bundle.rs

    - name: Check diff of bundle.rs
      id: diff
      run: |
        git add -N .
        git diff --name-only --exit-code
      continue-on-error: true

    - name: Commit and push bundle.rs
      if: steps.diff.outcome == 'failure'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub"
        git config --global user.email "noreply@github.com"
        git add .
        git commit -m "[auto-bundler] bundle commit ${GITHUB_SHA}"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD
