name: doc

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  doc:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Clean doc
      run: cargo clean --doc

    - name: Run doc (KaTeX)
      run: RUSTDOCFLAGS="--html-in-header katex-header.html" cargo doc --no-deps --open

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc/
