# https://qiita.com/KakurenboUni/items/b47d9e6e3582e2149d63 が参考になります

name: verify

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    # required only if you want to verify Rust code
    - name: Set up Rust (1.70.0)
      run: |
        rustup set profile minimal
        rustup install 1.70.0
        rustup override set nightly

    # required by cargo-udeps
    - name: Set up Rust (nightly)
      run: |
        rustup set profile minimal
        rustup install nightly
        rustup override set nightly

    # required only if you set `languages.rust.list_dependencies_backend.kind` to `"cargo-udeps"`
    - name: Install cargo-udeps for Rust
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-udeps
        version: '0.1.47'
        args: --debug

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: oj-verify run
